### ISSUE TITLE
Content with etalab license are not easy to modify 

### ISSUE THREAD

**Issue by SamirSaidani** [etalab/licence-ouverte#10]
This is a general problem with this kind of open content license : they allow to modify the content but does not ask the author to provide the "source code" of the content.  I think that we must evolve the text of the license to ask the author to provide the source code of the content whenever possible. The source code might be the prompt of the image, or an svg file, which is an open format. 

See for instance this page :
https://www.vie-publique.fr/bibliotheque-multimedia

I'm authorized to modify jpg files but in practice it's like authorizing the modification of binary files: it's possible but since it's difficult, in practice you usually don't do it.

**Comment by bzg** [comment]
The license does reflect the legal obligations for French public administrations: since the provision of the "source code" (or its equivalent for non-source code contents) is not a legal obligation, I don't think it fits in the text of the license itself.

Etalab could of course mention this as a strong recommendation _somewhere_, though.

With the useful caveat: IANAL and I'm not working at Etalab anymore.

If nobody reply to this issue within two months, I will close it.

**Comment by bzg** [comment]
Well, we are way past the two months, so I'm closing this issue.

@SamirSaidani feel free to reopen it if you think it is important enough.
